### ISSUE TITLE
本地运行正常，放服务器就报错

### ISSUE THREAD

**Issue by 12123ads** [kukume/kukubot#45]
日志：
[root@wuhu kkbot]# java -jar kkbot.jar
2021-05-19 20:33:25,755 INFO  c.I.Y.d.ConfigManager@[main] - ConfigManager Init.
2021-05-19 20:33:26,018 INFO  c.I.Y.d.ConfigManager@[main] - ConfigManager Config Mode: dev.
2021-05-19 20:33:26,019 INFO  c.I.Y.d.ConfigManager@[main] - ConfigManager Init Success.
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at me.kuku.yuq.Start.main(Start.java:54)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.icecreamqaq.yuq.YuQStarter$Companion.start(YuQStarter.kt:31)
        at com.icecreamqaq.yuq.YuQStarter.start(YuQStarter.kt)
        ... 5 more
Caused by: java.lang.NoClassDefFoundError: javafx/beans/value/ChangeListener
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:635)
        at com.IceCreamQAQ.Yu.loader.AppClassloader.loadAppClass(AppClassloader.java:107)
        at com.IceCreamQAQ.Yu.loader.AppClassloader.loadClass(AppClassloader.java:70)
        at com.IceCreamQAQ.Yu.loader.AppClassloader.loadClass(AppClassloader.java:58)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at com.IceCreamQAQ.Yu.loader.AppLoader.getClasses(AppLoader.kt:188)
        at com.IceCreamQAQ.Yu.loader.AppLoader.load(AppLoader.kt:50)
        at com.IceCreamQAQ.Yu.DefaultApp.start(DefaultApp.kt:47)
        ... 11 more
Caused by: java.lang.ClassNotFoundException: javafx.beans.value.ChangeListener
        at java.lang.ClassLoader.findClass(ClassLoader.java:523)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at com.IceCreamQAQ.Yu.loader.AppClassloader.loadClass(AppClassloader.java:68)
        at com.IceCreamQAQ.Yu.loader.AppClassloader.loadClass(AppClassloader.java:58)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 21 more
系统:centos7.9

**Comment by kukume** [comment]
请使用oraclejdk，不要使用openjdk，因为openjdk不带javafx

**Comment by 12123ads** [comment]
额

**Comment by 12123ads** [comment]
![image](https://user-images.githubusercontent.com/69107029/118819987-6e74bd80-b8e8-11eb-8916-caeba2213033.png)
这应该装了吧

**Comment by kukume** [comment]
yum的软件包不带oraclejdk，需要去oracle官网下载，或者可以使用我博客带的压缩包，然后替换掉jar包，里面自带了oracle jdk

**Comment by 12123ads** [comment]
好的

**Comment by 12123ads** [comment]
![image](https://user-images.githubusercontent.com/69107029/118821882-3bcbc480-b8ea-11eb-90a8-23b0c1e6aae8.png)
换成你博客压缩包里的jar了，还是这样

**Comment by Cubik65536** [comment]
另外仍要提醒，如果生产环境一定需要OpenJDK或者使用yum等包管理器，[`Azul`](https://www.azul.com/downloads/) 可以满足这类需求

**Comment by Cubik65536** [comment]
> ![image](https://user-images.githubusercontent.com/69107029/118821882-3bcbc480-b8ea-11eb-90a8-23b0c1e6aae8.png)
> 换成你博客压缩包里的jar了，还是这样

建议确认./start.sh内或者启动命令的java路径配置是否正确

**Comment by 12123ads** [comment]
我直接java -jar启动的

**Comment by Cubik65536** [comment]
> 我直接java -jar启动的

java -jar的话，使用正确的java路径，或者替换环境变量

**Comment by 12123ads** [comment]
正确的java地址是什么，，，

**Comment by 12123ads** [comment]
正确的java路径是什么

**Comment by 12123ads** [comment]
![image](https://user-images.githubusercontent.com/69107029/118823299-771ac300-b8eb-11eb-8429-b823b00266d4.png)
这m没有Linux的包啊

**Comment by Cubik65536** [comment]
> 正确的java路径是什么

如果你单独解压了一个新的JDK二进制包，那就应该使用`解压路径/java -jar kukubot.jar`，单独安装的Java应该去看看默认安装路径

**Comment by 12123ads** [comment]
![image](https://user-images.githubusercontent.com/69107029/118825993-b77b4080-b8ed-11eb-86d6-e3ae6a916d64.png)
按了这个咋用

**Comment by Cubik65536** [comment]
> ![image](https://user-images.githubusercontent.com/69107029/118825993-b77b4080-b8ed-11eb-86d6-e3ae6a916d64.png)
> 按了这个咋用

Azul? 如果没有其他Java的话，直接java -jar即可
另请注意，Azul有带JavaFX的版本也有不带的版本

**Comment by 12123ads** [comment]
我用yum装了个java，咋办

**Comment by kukume** [comment]
java -jar 会使用环境变量指向的java启动
在压缩内执行 jdk1.8.0_251/bin/java -jar  xxxx.jar
来启动

**Comment by Cubik65536** [comment]
> 我用yum装了个java，咋办

remove it

**Comment by 12123ads** [comment]
压缩包没有那个文件啊

**Comment by kukume** [comment]
![image](https://user-images.githubusercontent.com/45278810/118830830-d5e33b00-b8f1-11eb-87e6-2d0344592a89.png)
没有吗？

**Comment by 12123ads** [comment]
Linux的包在哪下_(:3&nbsp;⌒ﾞ)_


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月19日(周三) 晚上10:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kukume/kukubot] 本地运行正常，放服务器就报错 (#45)




 

 没有吗？
 
&mdash;

**Comment by kukume** [comment]
![image](https://user-images.githubusercontent.com/45278810/118838132-03cb7e00-b8f8-11eb-933c-0e4c637a99ce.png)
真就啥都不看呗？
![image](https://user-images.githubusercontent.com/45278810/118838178-0e861300-b8f8-11eb-82ba-7762d0a2a5fc.png)

**Comment by 12123ads** [comment]
没看见这个💦


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月19日(周三) 晚上11:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kukume/kukubot] 本地运行正常，放服务器就报错 (#45)




 

 真就啥都不看呗？
 
 
&mdash;

**Comment by kukume** [comment]
https://api.kuku.me/tb/pan/kuku/kuku-bot/kukubot-linux.tar.gz

**Comment by 12123ads** [comment]
http://128.199.127.232:8888/down/AphI9u05c59N
这咋办

**Comment by kukume** [comment]
参考 https://www.kuku.me/archives/6/#comment-152

**Comment by 12123ads** [comment]
好的我试试

**Comment by 12123ads** [comment]
http://128.199.127.232:8888/down/OiXM5UQntnlL
卡这了

**Comment by 12123ads** [comment]
![image](https://user-images.githubusercontent.com/69107029/119233063-ca924880-bb59-11eb-9b59-600766483ce0.png)
![image](https://user-images.githubusercontent.com/69107029/119233065-cbc37580-bb59-11eb-8d59-92ade363f4f2.png)
这是缺啥dll

**Comment by 12123ads** [comment]
系统是windows server 2012R2
